// components/CartDrawer.tsx
'use client'

import { useEffect, useRef, useState } from 'react'
import { useCart } from '@/lib/cart-context'

type Step = 'cart' | 'checkout' | 'success'
type SendStatus = 'idle' | 'sending' | 'error'

export default function CartDrawer() {
  const { items, isOpen, total, removeItem, updateQuantity, clearCart, closeCart } = useCart()
  const drawerRef = useRef<HTMLDivElement>(null)

  const [step, setStep] = useState<Step>('cart')
  const [form, setForm] = useState({ name: '', email: '', notes: '' })
  const [sendStatus, setSendStatus] = useState<SendStatus>('idle')

  // Close on Escape key
  useEffect(() => {
    const handleKey = (e: KeyboardEvent) => {
      if (e.key === 'Escape' && isOpen) closeCart()
    }
    document.addEventListener('keydown', handleKey)
    return () => document.removeEventListener('keydown', handleKey)
  }, [isOpen, closeCart])

  // Prevent body scroll when open
  useEffect(() => {
    document.body.style.overflow = isOpen ? 'hidden' : ''
    return () => { document.body.style.overflow = '' }
  }, [isOpen])

  // Reset to cart step when drawer closes
  useEffect(() => {
    if (!isOpen) {
      setStep('cart')
      setSendStatus('idle')
    }
  }, [isOpen])

  const handleFormChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => {
    setForm(prev => ({ ...prev, [e.target.name]: e.target.value }))
  }

  const handleSubmitOrder = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault()
    setSendStatus('sending')
    try {
      const res = await fetch('/api/orders', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          customerName: form.name,
          customerEmail: form.email,
          notes: form.notes,
          items,
          total,
        }),
      })
      if (res.ok) {
        clearCart()
        setForm({ name: '', email: '', notes: '' })
        setSendStatus('idle')
        setStep('success')
      } else {
        setSendStatus('error')
      }
    } catch {
      setSendStatus('error')
    }
  }

  return (
    <>
      {/* Backdrop */}
      {isOpen && (
        <div
          className="fixed inset-0 bg-black/50 z-40 transition-opacity"
          onClick={closeCart}
          aria-hidden="true"
        />
      )}

      {/* Drawer */}
      <div
        ref={drawerRef}
        className={`fixed top-0 right-0 h-full w-full max-w-sm bg-white shadow-2xl z-50 flex flex-col transition-transform duration-300 ${
          isOpen ? 'translate-x-0' : 'translate-x-full'
        }`}
        role="dialog"
        aria-modal="true"
        aria-label="Shopping cart"
      >
        {/* Header */}
        <div className="flex items-center justify-between p-4 border-b" style={{ borderColor: '#ede9df' }}>
          <div className="flex items-center gap-2">
            {step === 'checkout' && (
              <button
                onClick={() => { setStep('cart'); setSendStatus('idle') }}
                className="p-1 rounded-full hover:bg-gray-100 transition-colors text-gray-500 hover:text-gray-700 text-sm"
                aria-label="Back to cart"
              >
                ←
              </button>
            )}
            <h2 className="text-xl font-bold" style={{ color: '#8B4513' }}>
              {step === 'cart' && 'Your Cart'}
              {step === 'checkout' && 'Your Details'}
              {step === 'success' && 'Order Sent!'}
            </h2>
          </div>
          <button
            onClick={closeCart}
            className="p-2 rounded-full hover:bg-gray-100 transition-colors text-gray-500 hover:text-gray-700"
            aria-label="Close cart"
          >
            ✕
          </button>
        </div>

        {/* Body */}
        <div className="flex-1 overflow-y-auto p-4">

          {/* Success */}
          {step === 'success' && (
            <div className="flex flex-col items-center justify-center h-full text-center gap-4 px-4">
              <div className="text-6xl">🥜</div>
              <h3 className="text-2xl font-bold" style={{ color: '#8B4513' }}>Order Received!</h3>
              <p className="text-gray-600 text-sm leading-relaxed">
                We&apos;ve emailed you a confirmation and will be in touch shortly to arrange payment and pickup.
              </p>
              <button
                onClick={closeCart}
                className="btn-primary mt-2"
              >
                Continue Shopping
              </button>
            </div>
          )}

          {/* Cart items */}
          {step === 'cart' && (
            items.length === 0 ? (
              <div className="flex flex-col items-center justify-center h-full text-center text-gray-500 gap-4">
                <span className="text-5xl">🛒</span>
                <p className="text-lg font-medium">Your cart is empty</p>
                <p className="text-sm">Add some delicious nuts to get started!</p>
              </div>
            ) : (
              <ul className="space-y-4">
                {items.map(item => (
                  <li key={item.id} className="flex items-start gap-3 p-3 rounded-lg" style={{ backgroundColor: '#f8f6f0' }}>
                    <div className="text-3xl">🥜</div>
                    <div className="flex-1 min-w-0">
                      <p className="font-semibold text-sm text-gray-800 leading-tight">{item.name}</p>
                      <p className="text-sm font-bold mt-1" style={{ color: '#ff6b35' }}>
                        ${(item.price * item.quantity).toFixed(2)}
                      </p>
                      <div className="flex items-center gap-2 mt-2">
                        <button
                          onClick={() => updateQuantity(item.id, item.quantity - 1)}
                          className="w-8 h-8 rounded-full border font-bold text-lg flex items-center justify-center hover:bg-gray-200 transition-colors"
                          style={{ borderColor: '#8B4513', color: '#8B4513' }}
                          aria-label={`Decrease quantity of ${item.name}`}
                        >
                          −
                        </button>
                        <span className="w-6 text-center font-semibold">{item.quantity}</span>
                        <button
                          onClick={() => updateQuantity(item.id, item.quantity + 1)}
                          className="w-8 h-8 rounded-full border font-bold text-lg flex items-center justify-center hover:bg-gray-200 transition-colors"
                          style={{ borderColor: '#8B4513', color: '#8B4513' }}
                          aria-label={`Increase quantity of ${item.name}`}
                        >
                          +
                        </button>
                      </div>
                    </div>
                    <button
                      onClick={() => removeItem(item.id)}
                      className="text-gray-400 hover:text-red-500 transition-colors text-sm p-1"
                      aria-label={`Remove ${item.name} from cart`}
                    >
                      ✕
                    </button>
                  </li>
                ))}
              </ul>
            )
          )}

          {/* Checkout form */}
          {step === 'checkout' && (
            <form id="checkout-form" onSubmit={handleSubmitOrder} className="space-y-4">
              <p className="text-sm text-gray-500">
                Enter your details and we&apos;ll confirm your order and arrange payment.
              </p>
              <div>
                <label htmlFor="checkout-name" className="block text-sm font-semibold mb-1 text-gray-700">
                  Name <span className="text-red-500">*</span>
                </label>
                <input
                  id="checkout-name"
                  name="name"
                  type="text"
                  required
                  value={form.name}
                  onChange={handleFormChange}
                  placeholder="Your name"
                  className="w-full border rounded-lg px-3 py-2.5 text-sm focus:outline-none focus:ring-2"
                  style={{ borderColor: '#ede9df', '--tw-ring-color': '#ff6b35' } as React.CSSProperties}
                />
              </div>
              <div>
                <label htmlFor="checkout-email" className="block text-sm font-semibold mb-1 text-gray-700">
                  Email <span className="text-red-500">*</span>
                </label>
                <input
                  id="checkout-email"
                  name="email"
                  type="email"
                  required
                  value={form.email}
                  onChange={handleFormChange}
                  placeholder="your@email.com"
                  className="w-full border rounded-lg px-3 py-2.5 text-sm focus:outline-none focus:ring-2"
                  style={{ borderColor: '#ede9df', '--tw-ring-color': '#ff6b35' } as React.CSSProperties}
                />
              </div>
              <div>
                <label htmlFor="checkout-notes" className="block text-sm font-semibold mb-1 text-gray-700">
                  Notes <span className="text-gray-400 font-normal">(optional)</span>
                </label>
                <textarea
                  id="checkout-notes"
                  name="notes"
                  rows={3}
                  value={form.notes}
                  onChange={handleFormChange}
                  placeholder="Pickup preferences, questions, etc."
                  className="w-full border rounded-lg px-3 py-2.5 text-sm focus:outline-none focus:ring-2 resize-none"
                  style={{ borderColor: '#ede9df', '--tw-ring-color': '#ff6b35' } as React.CSSProperties}
                />
              </div>
              {sendStatus === 'error' && (
                <p className="text-red-600 text-sm">
                  Something went wrong. Please try again or call us at (517) 410-9029.
                </p>
              )}
            </form>
          )}
        </div>

        {/* Footer */}
        {step === 'cart' && items.length > 0 && (
          <div className="p-4 border-t space-y-3" style={{ borderColor: '#ede9df' }}>
            <div className="flex justify-between items-center text-lg font-bold" style={{ color: '#8B4513' }}>
              <span>Total</span>
              <span>${total.toFixed(2)}</span>
            </div>
            <button
              onClick={() => setStep('checkout')}
              className="w-full py-3 rounded-full font-bold text-white text-center transition-all duration-200 hover:-translate-y-0.5 hover:shadow-lg"
              style={{ backgroundColor: '#ff6b35' }}
            >
              Place Order →
            </button>
            <div className="text-center">
              <div className="inline-flex items-center gap-1.5 text-xs text-gray-400 bg-gray-50 px-3 py-1.5 rounded-full">
                <span>💳</span>
                <span>Coming soon: Pay by card (Stripe)</span>
              </div>
            </div>
            <button
              onClick={clearCart}
              className="w-full text-xs text-gray-400 hover:text-red-500 transition-colors py-1"
            >
              Clear cart
            </button>
          </div>
        )}

        {step === 'checkout' && (
          <div className="p-4 border-t space-y-3" style={{ borderColor: '#ede9df' }}>
            <div className="flex justify-between items-center text-sm text-gray-500">
              <span>{items.reduce((n, i) => n + i.quantity, 0)} item{items.reduce((n, i) => n + i.quantity, 0) !== 1 ? 's' : ''}</span>
              <span className="font-bold" style={{ color: '#8B4513' }}>${total.toFixed(2)}</span>
            </div>
            <button
              type="submit"
              form="checkout-form"
              disabled={sendStatus === 'sending'}
              className="w-full py-3 rounded-full font-bold text-white text-center transition-all duration-200 hover:-translate-y-0.5 hover:shadow-lg disabled:opacity-60 disabled:cursor-not-allowed disabled:transform-none"
              style={{ backgroundColor: '#ff6b35' }}
            >
              {sendStatus === 'sending' ? 'Sending Order...' : 'Send Order →'}
            </button>
          </div>
        )}
      </div>
    </>
  )
}

// app/components/CartDrawer.vue
<script setup lang="ts">
import { ref, computed } from 'vue'
import { useCartStore } from '../stores/cart'
import { formatPrice } from '../lib/products'

const cart = useCartStore()

const orderDialogOpen = ref(false)
const form = ref({
  name: '',
  email: '',
  phone: '',
  fulfillment: 'pickup' as 'pickup' | 'delivery',
  deliveryAddress: '',
  payment: 'on-pickup' as 'on-pickup' | 'call',
  notes: '',
})
const submitting = ref(false)
const submitted = ref(false)
const orderRef = ref('')
const errorMessage = ref('')
const formTouched = ref(false)

const subtotal = computed(() => formatPrice(cart.subtotalCents))

function openOrderDialog() {
  cart.closeDrawer()
  // Close drawer first, then open dialog — prevents nested overlay on mobile
  setTimeout(() => { orderDialogOpen.value = true }, 50)
}

function closeOrderDialog() {
  if (formTouched.value && !submitted.value) {
    if (!confirm('Cancel your order? Your items will remain in your cart.')) return
  }
  orderDialogOpen.value = false
  submitted.value = false
  errorMessage.value = ''
  formTouched.value = false
}

async function submitOrder() {
  if (submitting.value) return
  submitting.value = true
  errorMessage.value = ''

  try {
    const payload = {
      name: form.value.name,
      email: form.value.email,
      phone: form.value.phone,
      fulfillment: form.value.fulfillment,
      deliveryAddress: form.value.fulfillment === 'delivery' ? form.value.deliveryAddress : undefined,
      payment: form.value.payment,
      items: cart.items.map(i => ({ id: i.id, quantity: i.quantity })),
      notes: form.value.notes || undefined,
    }

    const res = await $fetch<{ success: true; orderRef: string; message: string }>('/api/orders', {
      method: 'POST',
      body: payload,
    })

    orderRef.value = res.orderRef
    submitted.value = true
    // Only clear cart after confirmed 200 OK
    cart.clearCart()
  } catch (err: unknown) {
    const e = err as { data?: { message?: string } }
    errorMessage.value = e?.data?.message ?? 'Something went wrong. Please try again.'
  } finally {
    submitting.value = false
  }
}
</script>

<template>
  <Teleport to="body">
    <!-- Backdrop -->
    <Transition name="fade">
      <div
        v-if="cart.isDrawerOpen"
        class="fixed inset-0 bg-black/50"
        style="z-index:calc(var(--z-drawer) - 1);"
        aria-hidden="true"
        @click="cart.closeDrawer()"
      />
    </Transition>

    <!-- Cart drawer -->
    <div
      class="cart-drawer"
      :class="{ 'is-open': cart.isDrawerOpen }"
      role="dialog"
      aria-label="Shopping cart"
      aria-modal="true"
    >
      <div class="flex flex-col h-full">
        <!-- Header -->
        <div class="cart-drawer-header">
          <h2>Your Cart</h2>
          <button
            type="button"
            class="flex items-center justify-center transition-colors"
            style="width:var(--touch-target);height:var(--touch-target);color:var(--color-cream-light);"
            aria-label="Close cart"
            @click="cart.closeDrawer()"
          >
            <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" aria-hidden="true">
              <line x1="18" y1="6" x2="6" y2="18"/><line x1="6" y1="6" x2="18" y2="18"/>
            </svg>
          </button>
        </div>

        <!-- Empty state -->
        <div v-if="cart.items.length === 0" class="flex-1 flex flex-col items-center justify-center p-8 text-center gap-4">
          <div class="text-5xl" aria-hidden="true">🥜</div>
          <p style="font-family:var(--font-display);font-size:1.125rem;color:var(--color-denim);">Your cart is empty</p>
          <p class="text-sm" style="color:var(--color-text-muted);">Add some cinnamon roasted nuts to get started.</p>
          <NuxtLink
            to="/shop"
            class="inline-block font-bold px-6 py-3 rounded btn-vintage"
            style="background-color:var(--color-orange);color:white;"
            @click="cart.closeDrawer()"
          >
            Browse Products
          </NuxtLink>
        </div>

        <!-- Items list -->
        <ul v-else class="flex-1 overflow-y-auto p-4 space-y-4">
          <li
            v-for="item in cart.items"
            :key="item.id"
            class="flex items-center gap-3 pb-4 border-b last:border-0"
            style="border-color:var(--color-border);"
          >
            <div class="flex-1 min-w-0">
              <p class="font-bold text-sm truncate" style="color:var(--color-text);">{{ item.name }}</p>
              <p class="text-sm" style="color:var(--color-text-muted);">{{ formatPrice(item.priceInCents) }} each</p>
            </div>

            <!-- Quantity controls — 44px touch targets -->
            <div class="flex items-center gap-1">
              <button
                type="button"
                class="flex items-center justify-center rounded-md font-bold text-lg transition-colors"
                style="width:var(--touch-target);height:var(--touch-target);color:var(--color-denim);"
                :aria-label="`Decrease quantity of ${item.name}`"
                @click="cart.updateQuantity(item.id, item.quantity - 1)"
              >−</button>
              <span class="w-8 text-center font-bold text-sm" aria-live="polite">{{ item.quantity }}</span>
              <button
                type="button"
                class="flex items-center justify-center rounded-md font-bold text-lg transition-colors"
                style="width:var(--touch-target);height:var(--touch-target);color:var(--color-denim);"
                :aria-label="`Increase quantity of ${item.name}`"
                @click="cart.updateQuantity(item.id, item.quantity + 1)"
              >+</button>
            </div>

            <div class="text-right" style="min-width:4rem;">
              <p class="font-bold text-sm" style="font-family:var(--font-display);font-size:0.95rem;color:var(--color-denim);">{{ formatPrice(item.priceInCents * item.quantity) }}</p>
              <button
                type="button"
                class="text-xs hover:underline"
                style="color:var(--color-error);"
                :aria-label="`Remove ${item.name} from cart`"
                @click="cart.removeItem(item.id)"
              >Remove</button>
            </div>
          </li>
        </ul>

        <!-- Footer: total + CTA -->
        <div v-if="cart.items.length > 0" class="border-t p-4 space-y-3" style="border-color:var(--color-border);background-color:var(--color-cream);">
          <div class="flex justify-between font-bold" style="font-family:var(--font-display);font-size:1.1rem;color:var(--color-denim);">
            <span>Subtotal</span>
            <span>{{ subtotal }}</span>
          </div>
          <p class="text-xs" style="color:var(--color-text-muted);">Fulfillment & payment details collected at checkout.</p>
          <button
            type="button"
            class="w-full font-bold py-3 px-6 rounded btn-vintage transition-colors"
            style="background-color:var(--color-orange);color:white;"
            @click="openOrderDialog"
          >
            Place Order
          </button>
        </div>
      </div>
    </div>

    <!-- Order dialog -->
    <Transition name="fade">
      <div v-if="orderDialogOpen" class="fixed inset-0 flex items-center justify-center p-4" style="z-index:var(--z-dialog);">
        <!-- Dialog backdrop -->
        <div class="absolute inset-0 bg-black/60" aria-hidden="true" @click="closeOrderDialog" />

        <dialog
          open
          class="relative w-full max-h-[90vh] overflow-y-auto bg-white rounded-lg p-0"
          style="max-width:32rem;box-shadow:var(--shadow-offset-lg);"
          aria-labelledby="order-dialog-title"
          @cancel.prevent="closeOrderDialog"
        >
          <!-- Success state -->
          <div v-if="submitted" class="p-6 text-center space-y-4">
            <div class="text-5xl" aria-hidden="true">✅</div>
            <h2 id="order-dialog-title" style="font-family:var(--font-display);font-size:1.25rem;color:var(--color-denim);">Order Received!</h2>
            <p class="font-bold" style="color:var(--color-orange);">Reference: {{ orderRef }}</p>
            <p class="text-sm" style="color:var(--color-text-muted);">We'll be in touch within 24 hours to confirm your order and arrange payment.</p>
            <button
              type="button"
              class="font-bold px-6 py-3 rounded btn-vintage"
              style="background-color:var(--color-denim);color:white;"
              @click="orderDialogOpen = false"
            >Close</button>
          </div>

          <!-- Order form -->
          <div v-else>
            <!-- Dialog header -->
            <div
              class="flex items-center justify-between px-6 py-4"
              style="background-color:var(--color-denim);"
            >
              <h2 id="order-dialog-title" style="font-family:var(--font-display);font-size:1.125rem;color:var(--color-cream-light);">Place Your Order</h2>
              <button
                type="button"
                class="flex items-center justify-center"
                style="width:var(--touch-target);height:var(--touch-target);color:var(--color-cream-light);"
                aria-label="Close order form"
                @click="closeOrderDialog"
              >
                <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" aria-hidden="true">
                  <line x1="18" y1="6" x2="6" y2="18"/><line x1="6" y1="6" x2="18" y2="18"/>
                </svg>
              </button>
            </div>

            <div class="p-6 space-y-4">
              <!-- Order summary (first, per UX spec) -->
              <div class="rounded-lg p-4 border" style="background-color:var(--color-cream-light);border-color:var(--color-denim);">
                <h3 class="font-bold text-sm mb-2" style="color:var(--color-denim);">Order Summary</h3>
                <ul class="space-y-1 text-sm">
                  <li v-for="item in cart.items" :key="item.id" class="flex justify-between">
                    <span>{{ item.name }} × {{ item.quantity }}</span>
                    <span style="font-family:var(--font-display);font-size:0.85rem;">{{ formatPrice(item.priceInCents * item.quantity) }}</span>
                  </li>
                </ul>
                <div class="border-t mt-2 pt-2 flex justify-between font-bold" style="border-color:var(--color-border);">
                  <span>Total</span>
                  <span style="font-family:var(--font-display);">{{ subtotal }}</span>
                </div>
              </div>

              <!-- Error message -->
              <div
                v-if="errorMessage"
                role="alert"
                class="rounded-lg p-3 text-sm border"
                style="background-color:var(--color-error-light);border-color:var(--color-error);color:var(--color-error);"
              >{{ errorMessage }}</div>

              <form @submit.prevent="submitOrder" novalidate class="space-y-4" @input="formTouched = true">
                <!-- Contact fields -->
                <fieldset class="space-y-3">
                  <legend class="font-bold text-sm mb-2" style="color:var(--color-denim);">Contact Information</legend>
                  <div>
                    <label for="order-name" class="block text-sm font-bold mb-1">
                      Full Name <span style="color:var(--color-error);" aria-hidden="true">*</span>
                    </label>
                    <input
                      id="order-name"
                      v-model="form.name"
                      type="text"
                      required
                      autocomplete="name"
                      class="w-full px-3 py-2.5 text-sm rounded border"
                      style="border-color:var(--color-border);"
                      placeholder="Jane Smith"
                    />
                  </div>
                  <div>
                    <label for="order-email" class="block text-sm font-bold mb-1">
                      Email <span style="color:var(--color-error);" aria-hidden="true">*</span>
                    </label>
                    <input
                      id="order-email"
                      v-model="form.email"
                      type="email"
                      required
                      autocomplete="email"
                      class="w-full px-3 py-2.5 text-sm rounded border"
                      style="border-color:var(--color-border);"
                      placeholder="jane@example.com"
                    />
                  </div>
                  <div>
                    <label for="order-phone" class="block text-sm font-bold mb-1">
                      Phone <span style="color:var(--color-error);" aria-hidden="true">*</span>
                    </label>
                    <input
                      id="order-phone"
                      v-model="form.phone"
                      type="tel"
                      required
                      autocomplete="tel"
                      class="w-full px-3 py-2.5 text-sm rounded border"
                      style="border-color:var(--color-border);"
                      placeholder="(517) 555-1234"
                    />
                  </div>
                </fieldset>

                <!-- Fulfillment -->
                <fieldset class="space-y-2">
                  <legend class="font-bold text-sm mb-1" style="color:var(--color-denim);">Fulfillment</legend>
                  <label class="flex items-center gap-2 cursor-pointer">
                    <input type="radio" v-model="form.fulfillment" value="pickup" />
                    <span class="text-sm">Pickup at Farmer's Market</span>
                  </label>
                  <label class="flex items-center gap-2 cursor-pointer">
                    <input type="radio" v-model="form.fulfillment" value="delivery" />
                    <span class="text-sm">Local Delivery</span>
                  </label>
                  <div v-if="form.fulfillment === 'delivery'" class="mt-2">
                    <label for="order-address" class="block text-sm font-bold mb-1">Delivery Address</label>
                    <input
                      id="order-address"
                      v-model="form.deliveryAddress"
                      type="text"
                      autocomplete="street-address"
                      class="w-full px-3 py-2.5 text-sm rounded border"
                      style="border-color:var(--color-border);"
                      placeholder="123 Main St, Dimondale, MI"
                    />
                  </div>
                </fieldset>

                <!-- Payment -->
                <fieldset class="space-y-2">
                  <legend class="font-bold text-sm mb-1" style="color:var(--color-denim);">Payment</legend>
                  <label class="flex items-center gap-2 cursor-pointer">
                    <input type="radio" v-model="form.payment" value="on-pickup" />
                    <span class="text-sm">Pay at pickup (Venmo, Square, PayPal)</span>
                  </label>
                  <label class="flex items-center gap-2 cursor-pointer">
                    <input type="radio" v-model="form.payment" value="call" />
                    <span class="text-sm">Call me to arrange payment</span>
                  </label>
                </fieldset>

                <!-- Notes -->
                <div>
                  <label for="order-notes" class="block text-sm font-bold mb-1">Notes (optional)</label>
                  <textarea
                    id="order-notes"
                    v-model="form.notes"
                    rows="3"
                    class="w-full px-3 py-2.5 text-sm rounded border resize-none"
                    style="border-color:var(--color-border);"
                    placeholder="Allergies, special requests, gift message..."
                  />
                </div>

                <button
                  type="submit"
                  :disabled="submitting"
                  class="w-full font-bold py-3 px-6 rounded btn-vintage transition-colors disabled:opacity-60 disabled:cursor-not-allowed"
                  style="background-color:var(--color-orange);color:white;"
                >
                  {{ submitting ? 'Sending…' : 'Send Order' }}
                </button>
              </form>
            </div>
          </div>
        </dialog>
      </div>
    </Transition>
  </Teleport>
</template>

<style scoped>
.fade-enter-active, .fade-leave-active { transition: opacity 0.2s ease; }
.fade-enter-from, .fade-leave-to { opacity: 0; }
</style>
