// app/blog/page.tsx
import type { Metadata } from 'next'
import Link from 'next/link'
import { getPosts } from '@/lib/wordpress'

export const metadata: Metadata = {
  title: 'Blog — Recipes, Gift Guides & Behind the Scenes',
  description:
    'Recipes featuring cinnamon roasted nuts, seasonal gift guides, event recaps, and stories from The Nut Barn family business in Dimondale, Michigan.',
}

export default async function BlogPage() {
  const posts = await getPosts(12)

  return (
    <>
      {/* Hero */}
      <section
        className="py-16 text-center text-white"
        style={{ background: 'linear-gradient(135deg, #8B4513, #5c2d0e)' }}
      >
        <div className="max-w-2xl mx-auto px-4">
          <h1 className="text-4xl md:text-5xl font-bold mb-4">From The Nut Barn</h1>
          <p className="text-orange-200 text-lg">
            Recipes, gift ideas, market stories, and everything in between.
          </p>
        </div>
      </section>

      {/* Blog Grid */}
      <section className="py-16 px-4" style={{ backgroundColor: '#f8f6f0' }}>
        <div className="max-w-6xl mx-auto">
          {posts.length === 0 ? (
            <div className="text-center py-16">
              <div className="text-6xl mb-4">📝</div>
              <h2 className="text-2xl font-bold mb-2" style={{ color: '#8B4513' }}>
                Posts Coming Soon
              </h2>
              <p className="text-gray-600 mb-8">
                We&apos;re working on recipes, gift guides, and market stories. Check back soon!
              </p>
              <Link href="/shop" className="btn-primary">
                Shop Our Nuts →
              </Link>
            </div>
          ) : (
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
              {posts.map(post => (
                <article key={post.id} className="card flex flex-col">
                  {/* Image placeholder */}
                  <div
                    className="w-full h-48 rounded-lg mb-4 flex items-center justify-center text-4xl"
                    style={{ background: 'linear-gradient(135deg, #ede9df, #f8f6f0)' }}
                  >
                    🥜
                  </div>

                  {/* Categories */}
                  {post.categories.length > 0 && (
                    <div className="flex gap-1.5 flex-wrap mb-3">
                      {post.categories.map(cat => (
                        <span
                          key={cat}
                          className="text-xs font-semibold px-2 py-0.5 rounded-full"
                          style={{ backgroundColor: '#ede9df', color: '#8B4513' }}
                        >
                          {cat}
                        </span>
                      ))}
                    </div>
                  )}

                  <h2 className="text-lg font-bold mb-2 flex-1" style={{ color: '#8B4513' }}>
                    <Link
                      href={`/blog/${post.slug}`}
                      className="hover:underline"
                    >
                      {post.title}
                    </Link>
                  </h2>

                  <p className="text-gray-600 text-sm leading-relaxed mb-4">{post.excerpt}</p>

                  <div className="flex items-center justify-between mt-auto pt-4 border-t" style={{ borderColor: '#ede9df' }}>
                    <time className="text-xs text-gray-400">
                      {new Date(post.date).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}
                    </time>
                    <Link
                      href={`/blog/${post.slug}`}
                      className="text-sm font-semibold hover:underline"
                      style={{ color: '#ff6b35' }}
                    >
                      Read More →
                    </Link>
                  </div>
                </article>
              ))}
            </div>
          )}
        </div>
      </section>

      {/* CTA */}
      <section
        className="py-12 px-4 text-center text-white"
        style={{ backgroundColor: '#8B4513' }}
      >
        <h2 className="text-2xl font-bold mb-2">Inspired by a Recipe?</h2>
        <p className="text-orange-200 mb-6">
          Order fresh cinnamon roasted nuts to try it yourself.
        </p>
        <Link href="/shop" className="btn-primary">
          Shop Now →
        </Link>
      </section>
    </>
  )
}

// app/pages/blog/index.vue
<script setup lang="ts">
useHead({
  title: 'Blog — The Nut Barn',
  meta: [
    { name: 'description', content: "Stories, recipes, and market updates from The Nut Barn. Handcrafted cinnamon roasted nuts from Dimondale, Michigan." },
  ],
})

const MOCK_POSTS = [
  {
    id: '1',
    slug: 'why-cinnamon-roasted-nuts',
    title: 'Why We Chose Cinnamon Roasted Nuts',
    date: '2026-01-15',
    excerpt: 'The story behind our signature recipe — and why FIVE simple ingredients is all you need.',
  },
  {
    id: '2',
    slug: 'holt-farmers-market-guide',
    title: "A Guide to the Holt Farmer's Market",
    date: '2026-02-01',
    excerpt: 'What to expect, where to park, and where to find us every Saturday morning.',
  },
]

const { data: posts } = await useAsyncData('blog-posts', () => Promise.resolve(MOCK_POSTS))

function formatDate(dateStr: string): string {
  return new Date(dateStr).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })
}
</script>

<template>
  <div>
    <!-- Header -->
    <section class="px-4 py-14 text-center" style="background:var(--gradient-hero);color:var(--color-text-inverse);">
      <div class="mx-auto" style="max-width:var(--container-md);">
        <p class="eyebrow mb-2" style="color:var(--color-mustard);">The Nut Barn</p>
        <h1 style="font-size:clamp(2rem,5vw,3rem);color:var(--color-cream-light);">From the Barn</h1>
        <p class="mt-2" style="color:rgba(253,246,232,0.8);">Stories, tips, and market updates from The Nut Barn.</p>
      </div>
    </section>

    <div class="mx-auto px-4 py-12" style="max-width:var(--container-lg);">
      <!-- Empty state -->
      <div v-if="!posts?.length" class="text-center py-16">
        <p class="text-lg mb-2" style="color:var(--color-text-muted);">No posts yet.</p>
        <p style="color:var(--color-text-muted);">Follow us on Instagram <strong style="color:var(--color-denim);">@thenutbarn</strong> for updates!</p>
      </div>

      <!-- Post grid -->
      <ul v-else class="grid grid-cols-1 sm:grid-cols-2 gap-6">
        <li
          v-for="post in posts"
          :key="post.id"
          class="bg-white rounded-lg overflow-hidden card-vintage"
        >
          <!-- Image placeholder -->
          <div class="aspect-[16/9]" style="background:var(--gradient-product);" aria-hidden="true" />
          <div class="p-5">
            <p class="eyebrow mb-2">{{ formatDate(post.date) }}</p>
            <h2 class="mb-2" style="font-size:1.125rem;color:var(--color-denim);">{{ post.title }}</h2>
            <p class="text-sm mb-4" style="color:var(--color-text-muted);">{{ post.excerpt }}</p>
            <NuxtLink :to="`/blog/${post.slug}`" class="text-sm font-bold" style="color:var(--color-orange);">Read More →</NuxtLink>
          </div>
        </li>
      </ul>

      <!-- Shop CTA -->
      <div class="mt-12 text-center">
        <NuxtLink to="/shop" class="font-bold px-8 py-3.5 rounded btn-vintage" style="background-color:var(--color-orange);color:white;">
          Shop Our Nuts →
        </NuxtLink>
      </div>
    </div>
  </div>
</template>
