// app/pages/wholesale.vue
<script setup lang="ts">
import { ref } from 'vue'

useHead({
  title: 'Wholesale — The Nut Barn',
  meta: [
    { name: 'description', content: 'Bring The Nut Barn cinnamon roasted nuts to your store, event, or corporate gift program. Wholesale inquiries welcome.' },
  ],
})

const form = ref({
  name: '',
  companyName: '',
  email: '',
  phone: '',
  businessType: 'Gift Shop',
  estimatedVolume: 'Under 50 units/month',
  message: '',
})
const submitting = ref(false)
const successMessage = ref('')
const errorMessage = ref('')

const useCases = ["Gift shops & boutiques", "Farmer's market vendors", "Corporate gift programs", "Holiday events & parties", "Specialty grocery stores", "Wedding & event favors"]
const businessTypes = ['Gift Shop', "Farmer's Market", 'Corporate Gifts', 'Event Planning', 'Grocery / Specialty Food', 'Other']
const volumes = ['Under 50 units/month', '50–100 units/month', '100–500 units/month', '500+ units/month']

async function submit() {
  if (submitting.value) return
  submitting.value = true
  successMessage.value = ''
  errorMessage.value = ''

  try {
    const res = await $fetch<{ success: true; message: string }>('/api/contact', {
      method: 'POST',
      body: {
        name: form.value.name,
        email: form.value.email,
        subject: `Wholesale Inquiry — ${form.value.companyName}`,
        message: `Company: ${form.value.companyName}\nPhone: ${form.value.phone}\nBusiness Type: ${form.value.businessType}\nEstimated Volume: ${form.value.estimatedVolume}\n\n${form.value.message}`,
      },
    })
    successMessage.value = res.message
    form.value = { name: '', companyName: '', email: '', phone: '', businessType: 'Gift Shop', estimatedVolume: 'Under 50 units/month', message: '' }
  } catch (err: unknown) {
    const e = err as { data?: { message?: string } }
    errorMessage.value = e?.data?.message ?? 'Something went wrong. Please try again.'
  } finally {
    submitting.value = false
  }
}
</script>

<template>
  <div>
    <!-- Header -->
    <section class="px-4 py-14 text-center" style="background:var(--gradient-hero);color:var(--color-text-inverse);">
      <div class="mx-auto" style="max-width:var(--container-md);">
        <p class="eyebrow mb-2" style="color:var(--color-mustard);">B2B</p>
        <h1 style="font-size:clamp(2rem,5vw,3.5rem);color:var(--color-cream-light);">Wholesale</h1>
        <p class="mt-3 text-lg" style="color:rgba(253,246,232,0.85);">
          Bring The Nut Barn to your store, event, or corporate gift program.
        </p>
      </div>
    </section>

    <div class="mx-auto px-4 py-12" style="max-width:var(--container-xl);">
      <div class="grid grid-cols-1 md:grid-cols-2 gap-12 mb-12">
        <!-- Why wholesale -->
        <div>
          <h2 class="mb-6" style="color:var(--color-denim);">Who It's For</h2>
          <ul class="space-y-4">
            <li v-for="use in useCases" :key="use" class="flex items-center gap-3">
              <span style="color:var(--color-orange);font-weight:700;">✓</span>
              <span style="color:var(--color-text);">{{ use }}</span>
            </li>
          </ul>
        </div>

        <!-- Details -->
        <div class="rounded-lg p-6 card-vintage" style="background-color:var(--color-cream-light);border:2px solid var(--color-denim);">
          <h2 class="mb-4" style="color:var(--color-denim);">Wholesale Details</h2>
          <ul class="space-y-3 text-sm" style="color:var(--color-text-muted);">
            <li><strong style="color:var(--color-text);">Minimum order:</strong> Discuss with us — we're flexible for the right partner</li>
            <li><strong style="color:var(--color-text);">Pricing:</strong> Volume-based discounts available</li>
            <li><strong style="color:var(--color-text);">Freshness:</strong> Made to order — we don't keep excess inventory</li>
            <li><strong style="color:var(--color-text);">Custom packaging:</strong> Available for large orders (ask us)</li>
            <li><strong style="color:var(--color-text);">Lead time:</strong> Typically 1–2 weeks for wholesale orders</li>
          </ul>
        </div>
      </div>

      <!-- Inquiry form -->
      <div class="max-w-lg mx-auto">
        <h2 class="mb-6 text-center" style="color:var(--color-denim);">Send an Inquiry</h2>

        <div v-if="successMessage" role="status" class="mb-6 rounded-lg p-4 border" style="background-color:var(--color-success-light);border-color:var(--color-success);color:var(--color-success);">{{ successMessage }}</div>
        <div v-if="errorMessage" role="alert" class="mb-6 rounded-lg p-4 border" style="background-color:var(--color-error-light);border-color:var(--color-error);color:var(--color-error);">{{ errorMessage }}</div>

        <form @submit.prevent="submit" novalidate class="space-y-4">
          <div class="grid grid-cols-2 gap-4">
            <div>
              <label for="ws-name" class="block text-sm font-bold mb-1">Contact Name <span style="color:var(--color-error);" aria-hidden="true">*</span></label>
              <input id="ws-name" v-model="form.name" type="text" required autocomplete="name" class="w-full px-3 py-2.5 text-sm rounded border" style="border-color:var(--color-border);" placeholder="Jane Smith" />
            </div>
            <div>
              <label for="ws-company" class="block text-sm font-bold mb-1">Company Name <span style="color:var(--color-error);" aria-hidden="true">*</span></label>
              <input id="ws-company" v-model="form.companyName" type="text" required class="w-full px-3 py-2.5 text-sm rounded border" style="border-color:var(--color-border);" placeholder="Acme Gift Shop" />
            </div>
          </div>

          <div>
            <label for="ws-email" class="block text-sm font-bold mb-1">Email <span style="color:var(--color-error);" aria-hidden="true">*</span></label>
            <input id="ws-email" v-model="form.email" type="email" required autocomplete="email" class="w-full px-3 py-2.5 text-sm rounded border" style="border-color:var(--color-border);" placeholder="jane@acmegifts.com" />
          </div>

          <div>
            <label for="ws-phone" class="block text-sm font-bold mb-1">Phone</label>
            <input id="ws-phone" v-model="form.phone" type="tel" autocomplete="tel" class="w-full px-3 py-2.5 text-sm rounded border" style="border-color:var(--color-border);" placeholder="(517) 555-1234" />
          </div>

          <div>
            <label for="ws-type" class="block text-sm font-bold mb-1">Type of Business</label>
            <select id="ws-type" v-model="form.businessType" class="w-full px-3 py-2.5 text-sm rounded border bg-white" style="border-color:var(--color-border);">
              <option v-for="t in businessTypes" :key="t">{{ t }}</option>
            </select>
          </div>

          <div>
            <label for="ws-volume" class="block text-sm font-bold mb-1">Estimated Monthly Volume</label>
            <select id="ws-volume" v-model="form.estimatedVolume" class="w-full px-3 py-2.5 text-sm rounded border bg-white" style="border-color:var(--color-border);">
              <option v-for="v in volumes" :key="v">{{ v }}</option>
            </select>
          </div>

          <div>
            <label for="ws-message" class="block text-sm font-bold mb-1">Message</label>
            <textarea id="ws-message" v-model="form.message" rows="4" class="w-full px-3 py-2.5 text-sm rounded border resize-none" style="border-color:var(--color-border);" placeholder="Tell us about your business and what you're looking for..." />
          </div>

          <button type="submit" :disabled="submitting" class="w-full font-bold py-3 rounded btn-vintage disabled:opacity-60" style="background-color:var(--color-orange);color:white;">
            {{ submitting ? 'Sending…' : 'Send Inquiry' }}
          </button>
        </form>
      </div>
    </div>
  </div>
</template>

// app/wholesale/page.tsx
'use client'

import { useState } from 'react'

export default function WholesalePage() {
  const [form, setForm] = useState({
    name: '',
    business: '',
    email: '',
    quantity: '',
    message: '',
  })
  const [status, setStatus] = useState<'idle' | 'sending' | 'success' | 'error'>('idle')

  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>) => {
    setForm(prev => ({ ...prev, [e.target.name]: e.target.value }))
  }

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    setStatus('sending')
    try {
      const res = await fetch('/api/contact', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          name: form.name,
          email: form.email,
          subject: `Wholesale Inquiry — ${form.business}`,
          message: `Business: ${form.business}\nEstimated quantity: ${form.quantity}\n\n${form.message}`,
        }),
      })
      setStatus(res.ok ? 'success' : 'error')
    } catch {
      setStatus('error')
    }
  }

  return (
    <>
      {/* Hero */}
      <section
        className="py-16 text-center text-white"
        style={{ background: 'linear-gradient(135deg, #8B4513, #5c2d0e)' }}
      >
        <div className="max-w-2xl mx-auto px-4">
          <h1 className="text-4xl md:text-5xl font-bold mb-4">Wholesale & Bulk Orders</h1>
          <p className="text-orange-200 text-lg">
            Bring The Nut Barn to your business, event, or gift program.
          </p>
        </div>
      </section>

      <section className="py-16 px-4" style={{ backgroundColor: '#f8f6f0' }}>
        <div className="max-w-5xl mx-auto grid grid-cols-1 md:grid-cols-5 gap-12">
          {/* Info */}
          <div className="md:col-span-2 space-y-6">
            <h2 className="text-2xl font-bold" style={{ color: '#8B4513' }}>Great For</h2>
            <div className="space-y-4">
              {[
                { icon: '🏪', title: 'Retail / Gift Shops', body: 'Stock our nuts in your store. Customers love finding local, artisan snacks.' },
                { icon: '🍽️', title: 'Restaurants & Cafes', body: 'Add cinnamon roasted nuts to your menu as a topping, snack, or dessert component.' },
                { icon: '🎁', title: 'Corporate Gifting', body: 'Branded or unbranded gift sets for employee appreciation, client gifts, or events.' },
                { icon: '🎉', title: 'Events & Weddings', body: 'Personalized nut bags as party favors or dessert table features.' },
              ].map(item => (
                <div key={item.title} className="card">
                  <div className="text-2xl mb-1">{item.icon}</div>
                  <h3 className="font-bold text-sm mb-1" style={{ color: '#8B4513' }}>{item.title}</h3>
                  <p className="text-sm text-gray-600">{item.body}</p>
                </div>
              ))}
            </div>
          </div>

          {/* Form */}
          <div className="md:col-span-3 card">
            {status === 'success' ? (
              <div className="text-center py-8">
                <div className="text-5xl mb-4">✅</div>
                <h3 className="text-2xl font-bold mb-2" style={{ color: '#8B4513' }}>Inquiry Sent!</h3>
                <p className="text-gray-600">
                  Thanks for your interest! We&apos;ll be in touch within 1–2 business days with wholesale pricing and details.
                </p>
              </div>
            ) : (
              <form onSubmit={handleSubmit} className="space-y-5">
                <h2 className="text-xl font-bold mb-6" style={{ color: '#8B4513' }}>Wholesale Inquiry</h2>

                <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                  <div>
                    <label htmlFor="name" className="block text-sm font-semibold mb-1 text-gray-700">
                      Your Name <span className="text-red-500">*</span>
                    </label>
                    <input
                      id="name" name="name" type="text" required
                      value={form.name} onChange={handleChange}
                      className="w-full border rounded-lg px-3 py-2.5 text-sm focus:outline-none"
                      style={{ borderColor: '#ede9df' }}
                      placeholder="Jane Smith"
                    />
                  </div>
                  <div>
                    <label htmlFor="business" className="block text-sm font-semibold mb-1 text-gray-700">
                      Business Name <span className="text-red-500">*</span>
                    </label>
                    <input
                      id="business" name="business" type="text" required
                      value={form.business} onChange={handleChange}
                      className="w-full border rounded-lg px-3 py-2.5 text-sm focus:outline-none"
                      style={{ borderColor: '#ede9df' }}
                      placeholder="Acme Gift Shop"
                    />
                  </div>
                </div>

                <div>
                  <label htmlFor="email" className="block text-sm font-semibold mb-1 text-gray-700">
                    Email <span className="text-red-500">*</span>
                  </label>
                  <input
                    id="email" name="email" type="email" required
                    value={form.email} onChange={handleChange}
                    className="w-full border rounded-lg px-3 py-2.5 text-sm focus:outline-none"
                    style={{ borderColor: '#ede9df' }}
                    placeholder="jane@yourbusiness.com"
                  />
                </div>

                <div>
                  <label htmlFor="quantity" className="block text-sm font-semibold mb-1 text-gray-700">
                    Estimated Monthly Quantity
                  </label>
                  <select
                    id="quantity" name="quantity"
                    value={form.quantity} onChange={handleChange}
                    className="w-full border rounded-lg px-3 py-2.5 text-sm focus:outline-none bg-white"
                    style={{ borderColor: '#ede9df' }}
                  >
                    <option value="">Select a range...</option>
                    <option value="10–25 bags">10–25 bags</option>
                    <option value="25–50 bags">25–50 bags</option>
                    <option value="50–100 bags">50–100 bags</option>
                    <option value="100+ bags">100+ bags</option>
                    <option value="One-time event order">One-time event order</option>
                  </select>
                </div>

                <div>
                  <label htmlFor="message" className="block text-sm font-semibold mb-1 text-gray-700">
                    Tell us more
                  </label>
                  <textarea
                    id="message" name="message" rows={4}
                    value={form.message} onChange={handleChange}
                    className="w-full border rounded-lg px-3 py-2.5 text-sm focus:outline-none resize-y"
                    style={{ borderColor: '#ede9df' }}
                    placeholder="What products are you interested in? Any special packaging or branding needs?"
                  />
                </div>

                {status === 'error' && (
                  <p className="text-red-600 text-sm">
                    Something went wrong. Email us directly at thenutbarnllc@gmail.com.
                  </p>
                )}

                <button
                  type="submit"
                  disabled={status === 'sending'}
                  className="btn-primary w-full py-3 disabled:opacity-60"
                >
                  {status === 'sending' ? 'Sending...' : 'Send Wholesale Inquiry →'}
                </button>
              </form>
            )}
          </div>
        </div>
      </section>
    </>
  )
}
