// app/contact/page.tsx
'use client'

import { useState } from 'react'

export default function ContactPage() {
  const [form, setForm] = useState({ name: '', email: '', subject: '', message: '' })
  const [status, setStatus] = useState<'idle' | 'sending' | 'success' | 'error'>('idle')

  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>) => {
    setForm(prev => ({ ...prev, [e.target.name]: e.target.value }))
  }

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    setStatus('sending')
    try {
      const res = await fetch('/api/contact', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(form),
      })
      if (res.ok) {
        setStatus('success')
        setForm({ name: '', email: '', subject: '', message: '' })
      } else {
        setStatus('error')
      }
    } catch {
      setStatus('error')
    }
  }

  return (
    <>
      {/* Hero */}
      <section
        className="py-16 text-center text-white"
        style={{ background: 'linear-gradient(135deg, #8B4513, #5c2d0e)' }}
      >
        <div className="max-w-2xl mx-auto px-4">
          <h1 className="text-4xl md:text-5xl font-bold mb-4">Contact Us</h1>
          <p className="text-orange-200 text-lg">
            Questions, orders, events, or just want to say hi — we&apos;d love to hear from you.
          </p>
        </div>
      </section>

      <section className="py-16 px-4" style={{ backgroundColor: '#f8f6f0' }}>
        <div className="max-w-5xl mx-auto grid grid-cols-1 md:grid-cols-5 gap-12">
          {/* Contact Info */}
          <div className="md:col-span-2 space-y-6">
            <div>
              <h2 className="text-2xl font-bold mb-6" style={{ color: '#8B4513' }}>Get in Touch</h2>
              <div className="space-y-4">
                <div className="flex items-start gap-3">
                  <span className="text-2xl">📧</span>
                  <div>
                    <p className="font-semibold text-sm" style={{ color: '#8B4513' }}>Email</p>
                    <a
                      href="mailto:thenutbarnllc@gmail.com"
                      className="text-gray-600 hover:text-orange-600 transition-colors text-sm"
                    >
                      thenutbarnllc@gmail.com
                    </a>
                  </div>
                </div>
                <div className="flex items-start gap-3">
                  <span className="text-2xl">📞</span>
                  <div>
                    <p className="font-semibold text-sm" style={{ color: '#8B4513' }}>Phone</p>
                    <a
                      href="tel:+15174109029"
                      className="text-gray-600 hover:text-orange-600 transition-colors text-sm"
                    >
                      (517) 410-9029
                    </a>
                  </div>
                </div>
                <div className="flex items-start gap-3">
                  <span className="text-2xl">📍</span>
                  <div>
                    <p className="font-semibold text-sm" style={{ color: '#8B4513' }}>Location</p>
                    <p className="text-gray-600 text-sm">Dimondale, Michigan</p>
                  </div>
                </div>
              </div>
            </div>

            <div className="card">
              <h3 className="font-bold mb-3" style={{ color: '#8B4513' }}>Find Us</h3>
              <p className="text-sm text-gray-600 mb-1">
                🏪 Holt Farmer&apos;s Market — Every Saturday 9am–2pm
              </p>
              <p className="text-sm text-gray-500">Plus community events around Mid-Michigan.</p>
            </div>

            <div>
              <h3 className="font-bold mb-3" style={{ color: '#8B4513' }}>Follow Us</h3>
              <div className="flex gap-3">
                <a
                  href="https://www.facebook.com/thenutbarn"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="px-4 py-2 rounded-full text-sm font-semibold text-white hover:opacity-80 transition-opacity"
                  style={{ backgroundColor: '#1877F2' }}
                >
                  Facebook
                </a>
                <a
                  href="https://www.instagram.com/thenutbarn"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="px-4 py-2 rounded-full text-sm font-semibold text-white hover:opacity-80 transition-opacity"
                  style={{ background: 'linear-gradient(45deg, #f09433, #e6683c, #dc2743, #cc2366, #bc1888)' }}
                >
                  Instagram
                </a>
              </div>
            </div>
          </div>

          {/* Contact Form */}
          <div className="md:col-span-3 card">
            {status === 'success' ? (
              <div className="text-center py-8">
                <div className="text-5xl mb-4">✅</div>
                <h3 className="text-2xl font-bold mb-2" style={{ color: '#8B4513' }}>
                  Message Sent!
                </h3>
                <p className="text-gray-600">
                  Thanks for reaching out! We&apos;ll get back to you within 1–2 business days.
                </p>
              </div>
            ) : (
              <form onSubmit={handleSubmit} className="space-y-5">
                <h2 className="text-xl font-bold mb-6" style={{ color: '#8B4513' }}>
                  Send a Message
                </h2>

                <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                  <div>
                    <label htmlFor="name" className="block text-sm font-semibold mb-1 text-gray-700">
                      Name <span className="text-red-500">*</span>
                    </label>
                    <input
                      id="name"
                      name="name"
                      type="text"
                      required
                      value={form.name}
                      onChange={handleChange}
                      className="w-full border rounded-lg px-3 py-2.5 text-sm focus:outline-none focus:ring-2"
                      style={{ borderColor: '#ede9df', '--tw-ring-color': '#ff6b35' } as React.CSSProperties}
                      placeholder="Your name"
                    />
                  </div>
                  <div>
                    <label htmlFor="email" className="block text-sm font-semibold mb-1 text-gray-700">
                      Email <span className="text-red-500">*</span>
                    </label>
                    <input
                      id="email"
                      name="email"
                      type="email"
                      required
                      value={form.email}
                      onChange={handleChange}
                      className="w-full border rounded-lg px-3 py-2.5 text-sm focus:outline-none focus:ring-2"
                      style={{ borderColor: '#ede9df', '--tw-ring-color': '#ff6b35' } as React.CSSProperties}
                      placeholder="your@email.com"
                    />
                  </div>
                </div>

                <div>
                  <label htmlFor="subject" className="block text-sm font-semibold mb-1 text-gray-700">
                    Subject
                  </label>
                  <select
                    id="subject"
                    name="subject"
                    value={form.subject}
                    onChange={handleChange}
                    className="w-full border rounded-lg px-3 py-2.5 text-sm focus:outline-none focus:ring-2 bg-white"
                    style={{ borderColor: '#ede9df', '--tw-ring-color': '#ff6b35' } as React.CSSProperties}
                  >
                    <option value="">Select a topic...</option>
                    <option value="General Question">General Question</option>
                    <option value="Order Inquiry">Order Inquiry</option>
                    <option value="Event Inquiry">Book Us for an Event</option>
                    <option value="Wholesale Inquiry">Wholesale / Bulk Order</option>
                    <option value="Other">Other</option>
                  </select>
                </div>

                <div>
                  <label htmlFor="message" className="block text-sm font-semibold mb-1 text-gray-700">
                    Message <span className="text-red-500">*</span>
                  </label>
                  <textarea
                    id="message"
                    name="message"
                    required
                    rows={5}
                    value={form.message}
                    onChange={handleChange}
                    className="w-full border rounded-lg px-3 py-2.5 text-sm focus:outline-none focus:ring-2 resize-y"
                    style={{ borderColor: '#ede9df', '--tw-ring-color': '#ff6b35' } as React.CSSProperties}
                    placeholder="How can we help you?"
                  />
                </div>

                {status === 'error' && (
                  <p className="text-red-600 text-sm">
                    Something went wrong. Please try again or email us directly at thenutbarnllc@gmail.com.
                  </p>
                )}

                <button
                  type="submit"
                  disabled={status === 'sending'}
                  className="btn-primary w-full py-3 disabled:opacity-60 disabled:cursor-not-allowed disabled:transform-none"
                >
                  {status === 'sending' ? 'Sending...' : 'Send Message →'}
                </button>
              </form>
            )}
          </div>
        </div>
      </section>
    </>
  )
}

// app/pages/contact.vue
<script setup lang="ts">
import { ref } from 'vue'

useHead({
  title: 'Contact Us — The Nut Barn',
  meta: [
    { name: 'description', content: 'Get in touch with The Nut Barn. Questions, orders, or wholesale inquiries — we reply within 24 hours.' },
  ],
})

const form = ref({
  name: '',
  email: '',
  subject: 'General Question',
  message: '',
})
const submitting = ref(false)
const successMessage = ref('')
const errorMessage = ref('')

const subjects = [
  'General Question',
  'Order Question',
  'Wholesale Inquiry',
  'Other',
]

async function submit() {
  if (submitting.value) return
  submitting.value = true
  successMessage.value = ''
  errorMessage.value = ''

  try {
    const res = await $fetch<{ success: true; message: string }>('/api/contact', {
      method: 'POST',
      body: form.value,
    })
    successMessage.value = res.message
    form.value = { name: '', email: '', subject: 'General Question', message: '' }
  } catch (err: unknown) {
    const e = err as { data?: { message?: string } }
    errorMessage.value = e?.data?.message ?? 'Something went wrong. Please try again.'
  } finally {
    submitting.value = false
  }
}
</script>

<template>
  <div>
    <!-- Header -->
    <section class="px-4 py-12 text-center" style="background-color:var(--color-cream-dark);">
      <div class="mx-auto" style="max-width:var(--container-md);">
        <h1 style="font-size:clamp(2rem,5vw,3rem);color:var(--color-brown);">Contact Us</h1>
        <p class="mt-2" style="color:var(--color-text-muted);">We reply within 24 hours.</p>
      </div>
    </section>

    <div class="mx-auto px-4 py-12 grid grid-cols-1 md:grid-cols-3 gap-12" style="max-width:var(--container-xl);">
      <!-- Info sidebar -->
      <aside class="space-y-6">
        <div>
          <h2 class="mb-3" style="font-size:1.25rem;color:var(--color-brown);">Get in Touch</h2>
          <ul class="space-y-3 text-sm">
            <li>
              <p class="font-bold mb-0.5" style="color:var(--color-text);">Email</p>
              <a href="mailto:thenutbarnllc@gmail.com" style="color:var(--color-brown);">thenutbarnllc@gmail.com</a>
            </li>
            <li>
              <p class="font-bold mb-0.5" style="color:var(--color-text);">Phone</p>
              <a href="tel:5174109029" style="color:var(--color-brown);">(517) 410-9029</a>
            </li>
            <li>
              <p class="font-bold mb-0.5" style="color:var(--color-text);">Location</p>
              <p style="color:var(--color-text-muted);">Dimondale, Michigan</p>
            </li>
          </ul>
        </div>

        <!-- Wholesale callout -->
        <div class="rounded-xl p-4 border" style="background-color:var(--color-cream-warm);border-color:var(--color-border);">
          <h3 class="mb-2" style="font-size:1rem;color:var(--color-brown);">Wholesale Inquiries</h3>
          <p class="text-sm mb-3" style="color:var(--color-text-muted);">Interested in carrying The Nut Barn in your store or event?</p>
          <NuxtLink to="/wholesale" class="text-sm font-bold" style="color:var(--color-orange);">Learn about wholesale →</NuxtLink>
        </div>
      </aside>

      <!-- Contact form -->
      <div class="md:col-span-2">
        <!-- Success message -->
        <div
          v-if="successMessage"
          role="status"
          class="mb-6 rounded-xl p-4 border"
          style="background-color:var(--color-success-light);border-color:var(--color-success);color:var(--color-success);"
        >
          {{ successMessage }}
        </div>

        <!-- Error message -->
        <div
          v-if="errorMessage"
          role="alert"
          class="mb-6 rounded-xl p-4 border"
          style="background-color:var(--color-error-light);border-color:var(--color-error);color:var(--color-error);"
        >
          {{ errorMessage }}
        </div>

        <form @submit.prevent="submit" novalidate class="space-y-5">
          <div>
            <label for="contact-name" class="block text-sm font-bold mb-1">
              Full Name <span style="color:var(--color-error);" aria-hidden="true">*</span>
            </label>
            <input
              id="contact-name"
              v-model="form.name"
              type="text"
              required
              autocomplete="name"
              class="w-full px-3 py-2.5 rounded-lg border text-sm"
              style="border-color:var(--color-border);"
              placeholder="Jane Smith"
            />
          </div>

          <div>
            <label for="contact-email" class="block text-sm font-bold mb-1">
              Email <span style="color:var(--color-error);" aria-hidden="true">*</span>
            </label>
            <input
              id="contact-email"
              v-model="form.email"
              type="email"
              required
              autocomplete="email"
              class="w-full px-3 py-2.5 rounded-lg border text-sm"
              style="border-color:var(--color-border);"
              placeholder="jane@example.com"
            />
          </div>

          <div>
            <label for="contact-subject" class="block text-sm font-bold mb-1">Subject</label>
            <select
              id="contact-subject"
              v-model="form.subject"
              class="w-full px-3 py-2.5 rounded-lg border text-sm bg-white"
              style="border-color:var(--color-border);"
            >
              <option v-for="s in subjects" :key="s" :value="s">{{ s }}</option>
            </select>
          </div>

          <div>
            <label for="contact-message" class="block text-sm font-bold mb-1">
              Message <span style="color:var(--color-error);" aria-hidden="true">*</span>
            </label>
            <textarea
              id="contact-message"
              v-model="form.message"
              rows="6"
              required
              class="w-full px-3 py-2.5 rounded-lg border text-sm resize-none"
              style="border-color:var(--color-border);"
              placeholder="How can we help?"
            />
          </div>

          <button
            type="submit"
            :disabled="submitting"
            class="font-bold px-8 py-3 rounded-full transition-colors disabled:opacity-60 disabled:cursor-not-allowed"
            style="background-color:var(--color-orange);color:white;"
          >
            {{ submitting ? 'Sending…' : 'Send Message' }}
          </button>
        </form>
      </div>
    </div>
  </div>
</template>
